# 定义对象/Map集合
#user:
#  name: Tom
#  age: 18
 # gender: 男

# 定义数组/List/Set集合
#hooby:
#  - Java
#  - Game
#  - Sport

spring:
  application:
    name: springboot-mybatis-quickstart
  #配置数据库链接信息
  datasource:
    url: jdbc:mysql://localhost:3306/web01
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 212414
#开启mybatis日志输出
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl